Update Action Test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -56,9 +56,20 @@ jobs:
           docker run --name=daemon_ofvp -d -p 3000:3000/tcp -e PASSWORD_ENCRYPT -e COOKIE_SECRET -e MongoDB_URL -e NODE_ENV ghcr.io/ofvp-project/deamonmaneger:local
           screen -dm -L -Logfile /tmp/daemon_ofvp.log docker logs --follow daemon_ofvp
           while true; do
-            if cat /tmp/daemon_ofvp.log | grep -q "3000"; then exit 0; fi
+            if cat /tmp/daemon_ofvp.log | grep -q "3000"; then
+              if curl http://localhost:3000/users/v3; then
+                break
+              else
+                echo "Cannot request users endpoint"
+                exit 1
+              fi
+            fi
             sleep 1
           done
+          IP="$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' daemon_ofvp | sed "s|'||g")"
+          echo "Daemon IP: ${IP}"
+          echo "DAEMON_IP=${IP}" >> $GITHUB_ENV
+          exit 0
 
       - name: Install node packages
         run: npm install
@@ -66,4 +77,5 @@ jobs:
       - name: Run Test requests (${{ matrix.REQUETS }})
         env:
           REQUESTS: ${{ matrix.REQUETS }}
+          DAEMON_HOST: "http://${{ env.DAEMON_IP }}:3000"
         run: node test/index.js || (docker logs daemon_ofvp && exit 1)
